# Generated by Django 4.1.7 on 2023-03-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=150)),
                ('stdate', models.DateTimeField(null=True)),
                ('enddate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='leave_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('response', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('reg_salary', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
