# Generated by Django 4.1.7 on 2023-03-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_leave_leave_res_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='dept',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='des',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='fname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='lname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='emp_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
