# Generated by Django 4.1.7 on 2023-03-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_leave_dept_leave_des_leave_fname_leave_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emp_details',
            name='emp_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
