# Generated by Django 4.1.7 on 2023-04-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_emp_details_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='joindate',
            field=models.DateField(null=True),
        ),
    ]
