# Generated by Django 4.1.7 on 2023-04-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_emp_details_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='joindate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='stdate',
            field=models.DateField(null=True),
        ),
    ]
