# Generated by Django 4.1.7 on 2023-04-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_emp_details_joindate_alter_leave_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_res',
            name='response',
            field=models.CharField(default='no response', max_length=150),
        ),
    ]
